projects/dawdle/dawdle/components/home/blueprints.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import current_user

home_bp = Blueprint('home', __name__, url_prefix='/')


@home_bp.route('/')
def index_GET():
    if current_user.is_authenticated:
        return redirect(url_for('user.boards_GET'))

    return render_template('home/index.html')

projects/dawdle/dawdle/components/user/blueprints.py
from datetime import datetime

from bson.objectid import ObjectId
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user

from dawdle.components.auth.utils import send_verification_email
from dawdle.components.board.forms import CreateBoardForm
from dawdle.components.user.forms import (DeleteUserForm,
                                          UpdateAccountDetailsForm,
                                          UpdateEmailForm,
                                          UpdatePasswordForm)
from dawdle.components.user.models import User
from dawdle.components.user.utils import send_delete_account_email
from dawdle.utils import flash_params_message, no_cache

user_bp = Blueprint('user', __name__, url_prefix='/user')


@user_bp.route('/boards')
@login_required
@no_cache
def boards_GET():
    flash_params_message()

    return render_template(
        'user/boards.html',
        form=CreateBoardForm(request.form),
    )


@user_bp.route('/settings')
@login_required
def settings_GET():
    return redirect(url_for('user.settings_account_details_GET'))


@user_bp.route('/settings/account-details')
@login_required
def settings_account_details_GET():
    return render_template(
        'user/settings-account-details.html',
        form=UpdateAccountDetailsForm(request.form, obj=current_user),
    )


@user_bp.route('/settings/account-details', methods=['POST'])
@login_required
def settings_account_details_POST():
    form = UpdateAccountDetailsForm(request.form, obj=current_user)

    if not form.validate_on_submit():
        return render_template(
            'user/settings-account-details.html',
            form=form,
        ), 400

    if not form.update_needed():
        flash('No update needed.', 'info')
        return redirect(url_for('user.settings_account_details_POST'))

    form.populate_obj(current_user)
    current_user.last_updated = datetime.utcnow()
    current_user.save()

    flash('Your account details have been updated.', 'success')

    return redirect(url_for('user.settings_account_details_POST'))


@user_bp.route('/settings/update-email')
@login_required
def settings_update_email_GET():
    return render_template(
        'user/settings-update-email.html',
        form=UpdateEmailForm(request.form, email=current_user.email),
    )


@user_bp.route('/settings/update-email', methods=['POST'])
@login_required
def settings_update_email_POST():
    form = UpdateEmailForm(request.form, email=current_user.email)

    if not form.validate_on_submit():
        return render_template(
            'user/settings-update-email.html',
            form=form,
        ), 400

    if not form.update_needed():
        flash('No update needed.', 'info')
        return redirect(url_for('user.settings_update_email_POST'))

    current_user.active = False
    current_user.auth_id = ObjectId()
    current_user.email = form.email.data
    current_user.last_updated = datetime.utcnow()
    current_user.save()

    redirect_target = url_for('user.settings_update_email_POST')

    send_verification_email(current_user, redirect_target=redirect_target)

    return redirect(url_for(
        'auth.verify_resend_GET',
        email=form.email.data,
        next=redirect_target,
    ))


@user_bp.route('/settings/update-password')
@login_required
def settings_update_password_GET():
    return render_template(
        'user/settings-update-password.html',
        form=UpdatePasswordForm(request.form),
    )


@user_bp.route('/settings/update-password', methods=['POST'])
@login_required
def settings_update_password_POST():
    form = UpdatePasswordForm(request.form)

    if not form.validate_on_submit():
        return render_template(
            'user/settings-update-password.html',
            form=form,
        ), 400

    if not form.update_needed():
        flash('No update needed.', 'info')
        return redirect(url_for('user.settings_update_password_POST'))

    current_user.password = User.encrypt_password(form.new_password.data)
    current_user.auth_id = ObjectId()
    current_user.last_updated = datetime.utcnow()
    current_user.save()

    flash('Your password has been updated.', 'success')

    login_user(current_user)

    return redirect(url_for('user.settings_update_password_POST'))


@user_bp.route('/settings/delete-account')
@login_required
def settings_delete_account_GET():
    return render_template(
        'user/settings-delete-account.html',
        form=DeleteUserForm(request.form),
    )


@user_bp.route('/settings/delete-account', methods=['POST'])
@login_required
def settings_delete_account_POST():
    form = DeleteUserForm(request.form)

    if not form.validate_on_submit():
        return render_template(
            'user/settings-delete-account.html',
            form=form,
        ), 400

    send_delete_account_email(current_user)

    current_user.delete()

    flash('Your account has been deleted.', 'info')

    return redirect(url_for('home.index_GET'))

projects/dawdle/dawdle/templates/shared/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <title>{% block title %}Dawdle{% endblock %}</title>
  <meta name="description" content="A place to organise your projects.">
  <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon-32x32.png') }}">
  <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon-16x16.png') }}">
  <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='apple-touch-icon.png') }}">
  <link rel="mask-icon" href="{{ url_for('static', filename='safari-pinned-tab.svg') }}" color="#00d1b2">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <link rel="manifest" href="{{ url_for('static', filename='site.webmanifest') }}">
  <meta name="msapplication-config" content="{{ url_for('static', filename='browserconfig.xml') }}">
  <meta name="msapplication-TileColor" content="#00aba9">
  <meta name="theme-color" content="#ffffff">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.0/css/bulma.min.css" rel="stylesheet"
    integrity="sha256-aPeK/N8IHpHsvPBCf49iVKMdusfobKo2oxF8lRruWJg=" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bulma-checkradio@1.1.1/dist/css/bulma-checkradio.min.css" rel="stylesheet"
    integrity="sha256-ej+83V4GB9ok2X22EvJ/ggEzzJ+gaZjm7G/Neq7wboQ=" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bulma-quickview@2.0.0/dist/css/bulma-quickview.min.css" rel="stylesheet"
    integrity="sha256-JtX5zJWvo1j4zBm4wb8sr42VE3ydQKl05Q6vhek6RV4=" crossorigin="anonymous">
  <link href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" rel="stylesheet"
    integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,700%7CFredoka+One&display=swap" rel="stylesheet">
  {% assets 'dawdle_css' %}
    <link href="{{ ASSET_URL }}" rel="stylesheet">
  {% endassets %}
</head>

<body>
  {% include 'shared/header.html' %}

  <main class="{{ container_classes }}">
    <div class="notification is-marginless is-radiusless is-hidden has-text-weight-bold js-notification">
      <button type="button" class="delete js-notification-close" aria-label="close"></button>
      <span class="js-notification-text"></span>
    </div>
    {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="notification is-marginless is-radiusless is-{{category}} has-text-weight-bold">
            <button type="button" class="delete js-notification-close" aria-label="close"></button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
  </main>

  {% include 'shared/footer.html' %}

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"
    integrity="sha256-KM512VNnjElC30ehFwehXjx1YCHPiQkOPmqnrWtpccM=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"
    integrity="sha256-AAhU14J4Gv8bFupUUcHaPQfvrdNauRHMt+S4UVcaJb0=" crossorigin="anonymous"></script>  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.19/lodash.min.js"
    integrity="sha512-/A6lxqQJVUIMnx8B/bx/ERfeuJnqoWPJdUxN8aBj+tZYL35O998ry7UUGoN65PSUNlJNrqKZrDENi4i1c3zy4Q==" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/shave/2.5.9/jquery.shave.min.js"
    integrity="sha256-dgPV6UA48kYYXQIGyCe9z6WZJd/djLmyQg1UcIlhr7Q=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bulma-quickview@2.0.0/dist/js/bulma-quickview.min.js"
    integrity="sha256-21aydKMZ29jHJNw67RbF19paw+q0TFKcKRDxi8MPLxM=" crossorigin="anonymous"></script>
  <script>
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token() }}');
        }
      }
    });
  </script>
  {% assets 'dawdle_js' %}
    <script src="{{ ASSET_URL }}"></script>
  {% endassets %}
</body>

</html>

projects/dawdle/dawdle/templates/shared/footer.html
<footer class="footer">
  <div class="columns is-multiline">
    <div class="column is-6 has-text-left-tablet">
      <a href="{{ url_for('contact.index_GET') }}">Contact</a>
    </div>
    <div class="column is-6 has-text-right-tablet">
      {{ version }}
      <span class="separator"></span>
      <a href="https://github.com/vanillaSlice/the-mono/tree/main/projects/dawdle">GitHub</a>
      <span class="separator"></span>
      Made with 🎧 by <a href="https://www.mikelowe.xyz/">Mike</a>
    </div>
  </div>
</footer>

projects/dawdle/dawdle/templates/shared/header.html
<header class="header">
  <nav class="navbar is-transparent js-navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="{{ url_for('home.index_GET') }}">
        <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Dawdle: A place to organise your projects"
          width="112" height="28">
      </a>
      <a role="button" class="navbar-burger js-navbar-burger" aria-label="menu" aria-expanded="false">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div class="navbar-menu js-navbar-menu">
      <div class="navbar-start">
        {% if current_user.is_authenticated %}
          <a class="navbar-item" href="{{ url_for('user.boards_GET') }}">
            Boards
          </a>
        {% endif %}
      </div>
      <div class="navbar-end">
        {% if current_user.is_authenticated %}
          <div class="navbar-item has-dropdown is-hoverable">
            <div class="navbar-link user-link">
              <span class="user-icon has-background-primary has-text-white has-alt-text">
                {{ current_user.initials }}
              </span>
            </div>
            <div class="navbar-dropdown is-right">
              <a class="navbar-item" href="{{ url_for('user.settings_GET') }}">
                Settings
              </a>
              <a class="navbar-item" href="{{ url_for('auth.logout_GET') }}">
                Log Out
              </a>
            </div>
          </div>
        {% else %}
          <div class="navbar-item">
            <div class="buttons">
              <a class="button is-primary has-text-weight-bold" href="{{ url_for('auth.sign_up_GET') }}">
                Sign Up
              </a>
              <a class="button is-light has-text-weight-bold" href="{{ url_for('auth.login_GET') }}">
                Log In
              </a>
            </div>
          </div>
        {% endif %}
      </div>
    </div>
  </nav>
</header>

projects/dawdle/dawdle/templates/shared/utils.html
{% macro render_form_errors(form) %}
  {% if form.errors %}
    <div class="notification is-danger js-form-errors">
      <button type="button" class="delete js-notification-close" aria-label="close"></button>
      <div class="content">
        <ul class="js-form-errors-list">
          {% for field_errors in form.errors.values() %}
            {% for error in field_errors %}
              <li class="has-text-weight-bold">
                {{ error }}
              </li>
            {% endfor %}
          {% endfor %}
        </ul>
      </div>
    </div>
  {% endif %}
{% endmacro %}

{% macro render_checkbox(field) %}
  <div class="field">
    <div class="control">
      {{ field(class='is-checkradio', type='checkbox', **kwargs) | safe }}
      <label class="checkbox" for="{{ field.id }}">
        {{ field.label.text }}
      </label>
    </div>
  </div>
{% endmacro %}

{% macro render_password(field, show_help=False) %}
  {% set classes = 'input js-form-field js-password' %}
  {% if field.errors %}
    {% set classes = classes + ' is-danger' %}
  {% endif %}
  <div class="field js-form-field-container">
    {{ field.label(class='label') }}
    <div class="field has-addons">
      <div class="control is-expanded has-icons-left">
        {{ field(class=classes,
                  type='password',
                  placeholder='e.g. ••••••••••••',
                  autocomplete='off',
                  autocorrect='off',
                  autocapitalize='off',
                  spellcheck='false',
                  **kwargs) | safe }}
        <span class="icon is-small is-left">
          <i class="fas fa-lock"></i>
        </span>
      </div>
      <div class="control">
        <button
          type="button"
          class="button is-primary {{ 'is-danger' if field.errors }} js-password-mask"
          aria-label="mask/unmask password"
        >
          <span class="icon is-small">
            <i class="fas fa-eye js-password-mask-icon"></i>
          </span>
        </button>
      </div>
    </div>
    {% if show_help %}
      <p class="help {{ 'is-danger' if field.errors }} js-help">
        Minimum 8 characters
      </p>
    {% endif %}
  </div>
{% endmacro %}

{% macro render_textarea(field, left_icon_classes=None, help=None) %}
  {% set classes = 'input textarea js-form-field' %}
  {% if field.errors %}
    {% set classes = classes + ' is-danger' %}
  {% endif %}
  <div class="field js-form-field-container">
    {{ field.label(class='label') }}
    <div class="control {{ 'has-icons-left' if left_icon_classes }}">
      {{ field(class=classes, **kwargs) | safe }}
      {% if left_icon_classes %}
        <span class="icon is-small is-left">
          <i class="{{ left_icon_classes }}"></i>
        </span>
      {% endif %}
    </div>
    {% if help %}
      <p class="help {{ 'is-danger' if field.errors }} js-help">
        {{ help }}
      </p>
    {% endif %}
  </div>
{% endmacro %}

{% macro render_select(field, left_icon_classes=None, help=None) %}
  <div class="field js-form-field-container">
    {{ field.label(class='label') }}
    <div class="control {{ 'has-icons-left' if left_icon_classes }}">
      <div class="select is-fullwidth {{ 'is-danger' if field.errors }} js-form-field ">
        {{ field(**kwargs) | safe }}
        {% if left_icon_classes %}
          <span class="icon is-small is-left">
            <i class="{{ left_icon_classes }}"></i>
          </span>
        {% endif %}
      </div>
    </div>
    {% if help %}
      <p class="help {{ 'is-danger' if field.errors }} js-help">
        {{ help }}
      </p>
    {% endif %}
  </div>
{% endmacro %}

{% macro render_form_field(field, left_icon_classes=None, help=None) %}
  {% set classes = 'input js-form-field' %}
  {% if field.errors %}
    {% set classes = classes + ' is-danger' %}
  {% endif %}
  <div class="field js-form-field-container">
    {{ field.label(class='label') }}
    <div class="control {{ 'has-icons-left' if left_icon_classes }}">
      {{ field(class=classes, **kwargs) | safe }}
      {% if left_icon_classes %}
        <span class="icon is-small is-left">
          <i class="{{ left_icon_classes }}"></i>
        </span>
      {% endif %}
    </div>
    {% if help %}
      <p class="help {{ 'is-danger' if field.errors }} js-help">
        {{ help }}
      </p>
    {% endif %}
  </div>
{% endmacro %}